git:
    submodules: false

language: cpp

sudo: required
dist: trusty

os: linux
compiler: gcc

install:
  - sudo apt-get install libpoco-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
